name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from Cargo.toml
        id: get_version
        run: echo VERSION=$(cargo metadata --format-version 1 | jq -r '.packages[] | select(.name=="xtlid") | .version') >> $GITHUB_ENV

      - name: Log in to crates.io
        run: cargo login ${{ secrets.CRATES_IO_TOKEN }}

      - name: Publish crate
        run: cargo publish

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          files: src/xtlid.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

